### ISSUE TITLE
Add a parameter to set a delay to avoid rate limiting (1 hour ban from Chocolatey)

### ISSUE THREAD

**Issue by lebarsfa** [robertZaufall/ChocolateStoreCore#61]
When downloading a list of multiple packages, we are often "rate limited" (see https://docs.chocolatey.org/en-us/community-repository/community-packages-disclaimer#rate-limiting ). 
To avoid that, it would be good to add a parameter to set a delay between downloads from chocolatey.org. This was done in the last update I know of the original ChocolateStore project (see https://github.com/BahKoo/ChocolateStore/network ) in https://github.com/sr258/ChocolateStore/commit/fee515ef6b5e9c4b285d64f72641c97449391431 .

Here are my logs and configuration files if needed:
[log20240804.txt](https://github.com/user-attachments/files/16487860/log20240804.txt)
[download.txt](https://github.com/user-attachments/files/16487859/download.txt)
[appsettings.json](https://github.com/user-attachments/files/16487861/appsettings.json)

**Comment by robertZaufall** [comment]
I added a new version. Please check it out.

**Comment by lebarsfa** [comment]
Many thanks. I confirm that with the new parameter `HttpDelay` set to `5` in v1.2.1, I could download about 50 packages in 5 min without problems of rate limiting.

Here are my logs and configuration files if needed (there are errors but those are due to temporary download problems specific to some external file servers, or for `gstreamer-mingw` package it is because the download URLs are generated from PowerShell variables):
[log20240805.txt](https://github.com/user-attachments/files/16496997/log20240805.txt)
[download.txt](https://github.com/user-attachments/files/16497018/download.txt)
[appsettings.json](https://github.com/user-attachments/files/16497031/appsettings.json)
