### ISSUE TITLE
Add a parameter to set the character separator between the package name and the package version when a cache folder is created to contain external binaries

### ISSUE THREAD

**Issue by lebarsfa** [robertZaufall/ChocolateStoreCore#62]
For e.g. `sysinternals` package version `2023.7.26`, the original ChocolateStore project creates a folder `sysinternals-2023.7.26` where the external binaries called by `sysinternals.2023.7.26.nupkg` are downloaded.

This new ChocolateStoreCore project now creates a folder `sysinternals.2023.7.26` (i.e. with a `.` in the middle instead of `-`). 

This is not a problem for the `sysinternals` package since it works well but it may cause conflicts for packages where we need/want to edit ourselves the `.nupkg` (e.g. some packages need manual modification to really work offline) since when we extract the `.nupkg`, its content would be merged with the folder containing existing (and possibly wrong) binaries, which might not be desired. 

That being said, it is not an important issue since an obvious workaround is to extract the `.nupkg` elsewhere but I would say it is a minor regression/breaking change compared to the original ChocolateStore project. A parameter to choose between the `.` or `-` (or something else) could be an idea for that.

**Comment by robertZaufall** [comment]
I added a new version. Please check it out.
