### ISSUE TITLE
vcredist140 package: add the ability to detect URL for external binaries in other `.ps1` files

### ISSUE THREAD

**Issue by lebarsfa** [robertZaufall/ChocolateStoreCore#63]
[vcredist140](https://community.chocolatey.org/packages/vcredist140) package is a dependency of quite a lot of packages but it does not fully follow Chocolatey guidelines which advise to avoid splitting the package install code among multiple `.ps1` files. 
The URL of the external binaries to download are probably missed by ChocolateStoreCore since they are defined in a file `data.ps1`. That was already an unsolved issue for the previous ChocolateStore project. The current workaround is to modify the package manually but it is updated quite often, possibly with security fixes.

I don't know if extending the detection of URL in other `.ps1` files in the same folder as `chocolateyInstall.ps1` (but maybe different from `chocolateyUninstall.ps1` and `chocolateyBeforeModify.ps1`?) could have drawbacks, maybe it could be added as an option that can be e.g. 0: default behavior as I described; 1: detect in all `.ps1` files, 2: only use `chocolateyInstall.ps1`.

**Comment by robertZaufall** [comment]
Hi, I added a new parameter `InstallFilesPattern` which defaults to `tools/(ChocolateyInstall\\.ps|data\\.ps)` (both files are addressed here). Please check it out.

**Comment by lebarsfa** [comment]
It seems an elegant solution for this type of problem. I confirm that it solves the problem without causing obvious issues.

Here are my logs and configuration files if needed (I add also the output of a test of offline installation in a clean virtual machine, the errors for `DotNet3.5` and `vcredist2013` are probably internal to the packages, for `nirlauncher` it is Windows Defender that makes quarantines, for `obs-studio` I was inconsistent between the versions I asked for `obs-studio` and `obs-studio.install`, for `pswindowsupdate` it is a particular type of package):
[offline_install_output.txt](https://github.com/user-attachments/files/16502431/offline_install_output.txt)
[log20240805.txt](https://github.com/user-attachments/files/16502434/log20240805.txt)
[download.txt](https://github.com/user-attachments/files/16502433/download.txt)
[appsettings.json](https://github.com/user-attachments/files/16502432/appsettings.json)

**Comment by robertZaufall** [comment]
> It seems an elegant solution for this type of problem. I confirm that it solves the problem without causing obvious issues.
> 
> Here are my logs and configuration files if needed (I add also the output of a test of offline installation in a clean virtual machine, the errors for `DotNet3.5` and `vcredist2013` are probably internal to the packages, for `nirlauncher` it is Windows Defender that makes quarantines, for `obs-studio` I was inconsistent between the versions I asked for `obs-studio` and `obs-studio.install`, for `pswindowsupdate` it is a particular type of package): [offline_install_output.txt](https://github.com/user-attachments/files/16502431/offline_install_output.txt) [log20240805.txt](https://github.com/user-attachments/files/16502434/log20240805.txt) [download.txt](https://github.com/user-attachments/files/16502433/download.txt) [appsettings.json](https://github.com/user-attachments/files/16502432/appsettings.json)


Thanks for your response.
I took a look at your logfile btw.
`gstreamer-mingw` is problematic, as there are several PowerShell variables used which have to be recursively evaluated and replaced at runtime which is not implemented by now.

**Comment by lebarsfa** [comment]
Yes, since `gstreamer-mingw` problem is probably complicated to solve automatically but simple to correct manually and it is not a package used by many people, maybe it is not worth the time to correct that for now. 

But maybe it could still be interesting to keep track of packages that are known to possibly have problems specifically offline and potential workarounds, here is what I noticed:
- `gstreamer-mingw`: need to follow https://docs.chocolatey.org/en-us/guides/create/recompile-packages/#how-to-internalizerecompile-an-existing-package-manually to modify `chocolateyInstall.ps1` with something similar to

```powershell
$url            = ".\gstreamer-mingw-1.20.4\gstreamer-1.0-${devel}${toolchain}-x86-${version}.msi"
$url64          = ".\gstreamer-mingw-1.20.4\gstreamer-1.0-${devel}${toolchain}-x86_64-${version}.msi"
```
and prepare manually the folder `gstreamer-mingw-1.20.4` with the `.msi` files, to download manually (assuming the ChocolateStoreCore parameters are as in [appsettings.json](https://github.com/user-attachments/files/16502432/appsettings.json)).
- `pswindowsupdate`: see instuctions in `chocolateyInstall.ps1` in 
[PSWindowsUpdate.2.2.1.4.nupkg.zip](https://github.com/user-attachments/files/16513104/PSWindowsUpdate.2.2.1.4.nupkg.zip).
- `libreoffice-still`: seems to check for updates or other stuff online, TBD...
- `miktex.install`: TBD...
- `qt6-base-dev`, `qt5-default`: check for hints on their package webpage and [qt.zip](https://github.com/user-attachments/files/16513272/qt.zip).

**Comment by robertZaufall** [comment]
The packages you mentioned are really not trivial to solve.
I too have a problem right now with the `yarn` package but no time and no need to solve it at the moment.
